### ISSUE TITLE
savicki.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#10]
ciasteczka

![ss214](https://user-images.githubusercontent.com/44813765/49341729-d5875480-f651-11e8-9112-facfff99be32.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`savicki.pl##.accept-rodo`
