### ISSUE TITLE
ospace.com.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#110]
ciasteczka

![ss244](https://user-images.githubusercontent.com/44813765/49752842-dce1da00-fcb1-11e8-8f4a-2969772e03d4.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
```
 Warning: is_file(): open_basedir restriction in effect. File(/home/tmdesign/ospace.com.pl/www/system/../../vendor/autoload.php) is not within the allowed path(s): (/home/tmdesign/ospace.com.pl/www:/home/tmdesign/.system/tmp:/usr/local/pear) in /home/tmdesign/ospace.com.pl/www/system/startup.php on line 89
```
