### ISSUE TITLE
wsqn.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#120]
ciasteczka

![ss254](https://user-images.githubusercontent.com/44813765/49754885-968f7980-fcb7-11e8-8fca-34ddb8b38663.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
```
!www.wsqn.pl#@##social_container
!www.wsqn.pl#@#.social_container
!www.wsqn.pl#@#.social_bookmarks
```

Social wycina, chyba fanboy...

**Comment by gargaamel** [comment]
Zgadza się, Fanboy' Social List wycina komunikat ciasteczkowy, podobnie jak Fanboy's Cookie List wycina komunikaty nieciasteczkowe o czym było wspominane tu https://github.com/gargaamel/polskie-ciasteczka-rodo-zgloszenia/issues/1#issuecomment-445555705, ech ten Fanboy...

**Comment by krystian3w** [comment]
Jak coś to wg zaleceń **`@`hawk:eye:116477** taką dziwną kreskę będziemy likwidować listą RSS i tam też wytnie się zduplikowany przycisk kontaktu, bo jest w stopce.

Sam nie wiedziałem gdzie wyciąć/ulepszyć...
