### ISSUE TITLE
krzysztonjan.com

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#124]
ciasteczka

![ss258](https://user-images.githubusercontent.com/44813765/49760389-a8c3e480-fcc4-11e8-8381-c8e489d56b41.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by gargaamel** [comment]
Mam takie pytanie czy ten pusty kontener celowo zostawiony i ma tak być, bo np. może się tam jakiś inny przydatny komunikat pokazać:

![ss263](https://user-images.githubusercontent.com/44813765/49762973-a87b1780-fccb-11e8-94f8-402d8162e1b7.png)

**Comment by krystian3w** [comment]
Czasem strony tak mają jak wycinana jest promocja wewnętrzna / tło i nikt nie naprawia tego, można by zostawić do obserwacji na kiedyś, czy jakiś inny pasek się pojawi - raczej jak nie ma innego ID to też go wytnie.

**Comment by gargaamel** [comment]
Widzę, że pasek jest już wycinany, więc zamykam.
