### ISSUE TITLE
gitara-sklep.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#126]
ciasteczka

![ss260](https://user-images.githubusercontent.com/44813765/49760715-749cf380-fcc5-11e8-82b8-ba079d0c5ff1.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by gargaamel** [comment]
Mam takie pytanie czy te puste miejsce ma tak zostać czy body powino być sylem podnieione do góry.

**Comment by krystian3w** [comment]
Myślę, że trzeba dźwignąć, zawsze dźwigaliśmy jak były takie bugi.

**Comment by krystian3w** [comment]
`gitara-sklep.pl##body:style(padding-top: 0 !important;)`
