### ISSUE TITLE
papciolandia.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#135]
ciasteczka

![ss242](https://user-images.githubusercontent.com/44813765/49811688-0b1ff200-fd64-11e8-89e7-8298add0d0f4.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
RWD szablonu leży:

![obraz](https://user-images.githubusercontent.com/35370833/49830830-93b58700-fd92-11e8-800b-0ad15e34eb86.png) |
--- |
