### ISSUE TITLE
diecezjaplocka.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#143]
RODO

![ss250](https://user-images.githubusercontent.com/44813765/49819640-43303080-fd76-11e8-92c5-f438573c8f04.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
I cookies "generyk" `##.cookies_block`.
