### ISSUE TITLE
bmi-online.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#144]
rodo

![ss251](https://user-images.githubusercontent.com/44813765/49819805-93a78e00-fd76-11e8-9afa-73e152a8f221.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
I u mnie wypływa cookies z braku "generyka".
