### ISSUE TITLE
diagmed.info.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#147]
ciasteczka

![ss254](https://user-images.githubusercontent.com/44813765/49820889-64dee700-fd79-11e8-85d8-8f4985b20f71.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by gargaamel** [comment]
Na operze dalej to jest.

**Comment by krystian3w** [comment]
`##div > aside.type-10.widget` widać jakiś luck z:

`##div.type-10.widget > aside.type-10.widget` niby większość tak miała.

**Comment by krystian3w** [comment]
```
aluzja.gorzow.pl,artgos.pl,diagmed.info.pl,hostgrafia.pl,itlab.pl,mojawww.com,naukajazdy-kowalik.pl,osrodek-terapii.com,puch-kotlowski.pl,sls.info.pl,swiatdeski.pl,tomiicars.com.pl,treningkrakow.pl,vagaru.pl##div > aside.type-10.widget
```

**Comment by gargaamel** [comment]
Już ponad 3 tygodnie obserwacji i filtr trzyma więc zamykam.
