### ISSUE TITLE
solidarnosckatowice.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#148]
ciasteczka

![ss255](https://user-images.githubusercontent.com/44813765/49821052-c901ab00-fd79-11e8-9220-dff56329cead.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by gargaamel** [comment]
Na Operze dalej to jest.

**Comment by krystian3w** [comment]
`solidarnosckatowice.pl##body > div:not([class]):not([id]) > div[style^="position: absolute;"]`

coś zrobiło psikusa z zmiennym: ` top: 0px; left: 0px;` są już bez pikseli
