### ISSUE TITLE
forum-bron.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#15]
rodo

![ss210](https://user-images.githubusercontent.com/44813765/49343776-7c2e1e00-f66f-11e8-9bcb-245cce2c842f.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

---

 z tylko RODO-Ciasteczkową

![ss-k3w](https://user-images.githubusercontent.com/35370833/49343984-ada7e900-f671-11e8-87ad-f418885a2b0e.png)

**Comment by krystian3w** [comment]
`##.rightside.cookie-box.cookieAcceptBox`

Takie mamy jako generyki?

- `pl##.cookie-box:not(body):not(html)`

- `pl##.cookieAcceptBox:not(body):not(html)`

**Comment by gargaamel** [comment]
U mnie tych ciasteczek nie ma bo u mnie wycina mi to Fanboy's Cookie List, ale wiem, że Polskie Filtry RODO-Ciasteczkowe są niezależne, więc spoko, blokuj jeśli chcesz, każdy blokuje co mu trzeba.

> krystian3w : Takie mamy jako generyki?

Nie.

**Comment by krystian3w** [comment]
`forum-bron.pl###phpbb_announcement[style="background-color:#f0eae1"]`

I też do obserwacji, czy kiedyś nagle nie zmienią zawartości lub niestety koloru tła.
