### ISSUE TITLE
forumtransportu.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#16]
ciasteczka

![ss211](https://user-images.githubusercontent.com/44813765/49344305-923edd00-f675-11e8-90dc-c3a7812a4559.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`forumtransportu.pl##table.glowna:nth-of-type(1) > tbody > tr > td`

różnią się czymś te elementy `.glowna`?

Dodatkowo nie ma zamykacza (ale skoro da się wyciąć ładnie a nie jak kiedyś całe stopki, to może być).

**Comment by gargaamel** [comment]
> krystian3w : różnią się czymś te elementy `.glowna`?

Nie.

**Comment by krystian3w** [comment]
Szkoda.
