### ISSUE TITLE
aforyzmy-cytaty.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#17]
ciasteczka

![ss212](https://user-images.githubusercontent.com/44813765/49344363-493b5880-f676-11e8-9bce-c8a90dcf41ee.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`aforyzmy-cytaty.pl##body > .alert`

nijaki i czekać na inne alerty.
