### ISSUE TITLE
stronghold.net.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#18]
ciasteczka

![ss213](https://user-images.githubusercontent.com/44813765/49344416-16de2b00-f677-11e8-8db1-d29e482d1a2d.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`###ci_info`
