### ISSUE TITLE
msportal.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#19]
ciasteczka

![ss214](https://user-images.githubusercontent.com/44813765/49344580-ac7aba00-f679-11e8-94d7-8bcffcb8963e.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`msportal.pl###stickynote`
