### ISSUE TITLE
mbeszczecin.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#20]
ciasteczka

![ss215](https://user-images.githubusercontent.com/44813765/49344655-b6e98380-f67a-11e8-8b20-0d4defd93524.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`###bpagencyCookieAll`
