### ISSUE TITLE
radentortodonta.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#21]
ciasteczka

![ss216](https://user-images.githubusercontent.com/44813765/49344674-029c2d00-f67b-11e8-8bfe-e16394700218.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`radentortodonta.pl###topbar`
