### ISSUE TITLE
bs-zwolen.com.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#22]
rodo

![ss217](https://user-images.githubusercontent.com/44813765/49344713-69214b00-f67b-11e8-93be-2f6857350686.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

---

cookies z tylko RODO-Ciasteczkową

`###cookie_info_box` / `###cookie_info_box2`

**Comment by gargaamel** [comment]
Jeśli o mnie chodzi to u mnie tych ciasteczek nie ma bo wycinają mi je dodatkowe listy (https://github.com/gargaamel/polskie-ciasteczka-rodo-zgloszenia/issues/15#issuecomment-443535749)

**Comment by krystian3w** [comment]
Dobrze, tylko doklejam by nie zapomnieć uzupełnić naszej listy, nie mam doświadczenia z generykami, to zostają w gestii **`@`hawk:eye:116477**.

**Comment by gargaamel** [comment]
Spoko, ja nic nie mam do tego, bo ja kolei doklejam komentarz, żeby nie wyjść na ślepca, który co chwilę przeocza jakiś komunikat i jest poprawiany przez kogoś.
