### ISSUE TITLE
gopr.org

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#29]
ciasteczka

![ss209](https://user-images.githubusercontent.com/44813765/49371751-cb6c6100-f6f8-11e8-897e-58c5914f4848.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`gopr.org###popupDiv`
