### ISSUE TITLE
allsporter.com

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#30]
ciasteczka

![ss210](https://user-images.githubusercontent.com/44813765/49371863-256d2680-f6f9-11e8-9d4a-1e14585b84ac.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`##.cookies-ct`
