### ISSUE TITLE
avanti.com.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#31]
ciasteczka

![ss211](https://user-images.githubusercontent.com/44813765/49371993-8268dc80-f6f9-11e8-813e-3685fa074943.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`###cookie-warn-wrapper`
