### ISSUE TITLE
sekretypiekna.net

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#32]
ciasteczka

![ss212](https://user-images.githubusercontent.com/44813765/49372071-c1972d80-f6f9-11e8-900a-e472cabc7c31.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`##.ba_cookie_bar`
