### ISSUE TITLE
zozsuchabeskidzka.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#33]
rodo

![ss213](https://user-images.githubusercontent.com/44813765/49372370-b264af80-f6fa-11e8-82f2-897816067a42.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
Jakie dziwne, nie ma przewijania z boku a się przewija i jeszcze te pielęgniarki pod zaciemniają komunikat.

**Comment by gargaamel** [comment]
Rzeczywiście strona uszkodzona, i to nie z winy filtrów czy adblockera, lecz z winy samej siebie, albo przeglądarki, na operze wygląda to tak przy wyłączonej liście Polskie Filtry RODO-Ciasteczkowe:

![ss208](https://user-images.githubusercontent.com/44813765/49435811-c0c4d100-f7b7-11e8-96de-a58d7daea0d7.png)

**Comment by krystian3w** [comment]
Może trzeba zobaczyć jak po zamknięciu komunikatów, czasem się naprawia, rzadko pomaga ubicie całego pluginu na pop-up.

**Comment by gargaamel** [comment]
W sumie to niech sami se naprawiają, zamykam.
