### ISSUE TITLE
recepturybonifratrow.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#34]
rodo

![ss214](https://user-images.githubusercontent.com/44813765/49373798-9b748c00-f6ff-11e8-918f-0405d6004f70.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`recepturybonifratrow.pl###x13popup-container, #x13popup-cover`
