### ISSUE TITLE
militaria-hobby.eu

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#35]
ciasteczka

![ss215](https://user-images.githubusercontent.com/44813765/49374016-54d36180-f700-11e8-9520-e52dac254fed.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`militaria-hobby.eu##+js(remove-attr.js,onLoad,body[onLoad="alert ('UWAGA! - Ta strona używa ciasteczek (cookies)')"])`

jak nie to można testować inne

**Comment by gargaamel** [comment]
Stary, znowu jak w https://github.com/gargaamel/polskie-ciasteczka-rodo-zgloszenia/issues/35, na Operze twój filtr działa ,a na Firefoxie już nie, ja już nie mam siły.

**Comment by gargaamel** [comment]
To może to race condition.

**Comment by gargaamel** [comment]
Widżę, że filtr został zmieniony na `militaria-hobby.eu##+js(abort-on-property-read.js, alert)`, który działa na obydwu przeglądarkach, oczywiście taki filtr ubija wszystkie alerty, jeśli takowe się pojawią, ale nie znalazłem na stronie żadnego innego alertu, więc zamykam jako naprawione.
