### ISSUE TITLE
panattonieurope.com/pl/ (2)

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#36]
ciasteczka i rodo (2in1) - reopen https://github.com/MajkiIT/polish-ads-filter/issues/10435, dalej to jest i na Firefoxie i na Operze

![ss216](https://user-images.githubusercontent.com/44813765/49383480-23b35b00-f719-11e8-8a84-b0daaeea92a3.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
Musiało mi się nie dodać lub trzeba lepiej niż:

```
panattonieurope.com##body:style(overflow: auto !important;)
panattonieurope.com###image-popup.txt-popup, #image-popup-bg
```
