### ISSUE TITLE
pruszczgdanski.pl [3]

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#37]
Reopen reopenu - https://github.com/MajkiIT/polish-ads-filter/issues/10404 bo dalej to jest na Firefoxie i na Operze - w commicie widać, że jakiś filtr dodany ale nie chwyta tego komunikatu, więc domniemam, że bug:

![ss217](https://user-images.githubusercontent.com/44813765/49384283-f8317000-f71a-11e8-930c-51abb80371f0.png)

**Comment by krystian3w** [comment]
Na Firefox nie mam.

**Comment by krystian3w** [comment]
Albo mam, bo EI wycina z góry jako jakiś irytujący widget.

**Comment by gargaamel** [comment]
Zostawiam dalej otwarte bo co prawda

<details not-open>
<summary>na Firefoxie jest ok:</summary>

![ss205](https://user-images.githubusercontent.com/44813765/49436357-3b422080-f7b9-11e8-88ac-6a89e3ab1c3d.png)

</details>
.

<details not-open>
<summary>ale na Operze zostają 2 paski przewijania:</summary>

![ss204](https://user-images.githubusercontent.com/44813765/49436381-485f0f80-f7b9-11e8-9472-0f9096c013b9.png)

</details>

**Comment by krystian3w** [comment]
ja miałem 1, ciekawe.

**Comment by krystian3w** [comment]
Dwa się robią, jak nie mam EI.

`##.ifancybox-margin, .ifancybox-lock, .ifancybox-lock body`

Jedno z dwóch pewnie zbędne.

**Comment by krystian3w** [comment]
W sumie chyba ślepa uliczka, bez cookies przy takich filtrach mam 1:

```
pruszczgdanski.pl###ifancybox-overlay115
pruszczgdanski.pl##.ifancybox-margin, .ifancybox-lock, .ifancybox-lock body:style(overflow: auto !important; margin-right: 0 !important;)
```

Chyba jakiś bug w suplemencie na komunikaty cookies.

**Comment by krystian3w** [comment]
> ![image](https://user-images.githubusercontent.com/35370833/49438349-61b68a80-f7be-11e8-8acc-34a6a7d76be0.png) |
--- |

Z EI filtr wykonuje się dla 3 elementów i jakby 3 naprawiał mi.

**Comment by krystian3w** [comment]
Cały czas zapominam, że EI nie jest przyjazne dla niedowidzących i wycina powiązany plugin z widgetem...

**Comment by gargaamel** [comment]
Potwierdzam, naprawione, zamykam.

**Comment by gargaamel** [comment]
Potwierdzam, naprawione, zamykam.
