### ISSUE TITLE
egrafik.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#43]
ciasteczka

![ss202](https://user-images.githubusercontent.com/44813765/49445989-705b6c80-f7d3-11e8-99af-c023fb8e7b28.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
> **Strict Standards** : Non-static method Advanced_Permalinks::get() should not be called statically in  **/blog/wp-content/plugins/advanced-permalinks/advanced-permalinks.php**  on line  **825**
> 
> **Strict Standards** : call_user_func_array() expects parameter 1 to be a valid callback, non-static method GoogleSitemapGeneratorLoader::Enable() should not be called statically in  **/blog/wp-includes/plugin.php**  on line  **123**
> 
> **Warning** : call_user_func_array() expects parameter 2 to be array, null given in  **/blog/wp-includes/plugin.php**  on line  **123**

**Comment by krystian3w** [comment]
```
###cookies_in1
###cookies1
```
