### ISSUE TITLE
psychiatria-poradnie.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#50]
rodo

![ss209](https://user-images.githubusercontent.com/44813765/49448285-d991ae80-f7d8-11e8-9548-abe8e0634ad0.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
obczaj takie coś:

```
###popup-message-window,
```

176 wykrytych elementów... :full_moon:.

**Comment by gargaamel** [comment]
Faktycznie, jakiś bug w uBO.

**Comment by krystian3w** [comment]
Nie wydaje mi się by wcześniej brak znaków po przecinku działał jak gwiazdka:

`##*`

![obraz](https://user-images.githubusercontent.com/35370833/49467953-e5df3100-f803-11e8-99d0-a454ad01b1b3.png) |
---- |

![obraz](https://user-images.githubusercontent.com/35370833/49467990-fa232e00-f803-11e8-8e27-c7b68d89ec9d.png) |
--- |
