### ISSUE TITLE
e-hotelarz.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#52]
rodo

![ss211](https://user-images.githubusercontent.com/44813765/49468270-bc72d500-f804-11e8-9401-511ad55c1a9f.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
I cookies bez dodatkowych list o międzynarodowym zasięgu.

**Comment by gargaamel** [comment]
A kto by używał tylko Polskie Filtry RODO-Ciasteczkowe bez używania Fanboy's Cookie List i/lub I don't care about cookies, to tak jak gdyby ktoś używał POL: polskie filtry do Adblocka i uBlocka bez używania EasyList albo Polish Privacy Filters bez używania Easy Privacy, znasz kogoś takiego?

**Comment by krystian3w** [comment]
W sumie też je masz na grafice, to ten biały pasek.

**Comment by krystian3w** [comment]
dziura po części z reklam i br, nie naprawiam więc na siłę.

**Comment by gargaamel** [comment]
> krystian3w : w sumie też je masz na grafice, to ten biały pasek.

Fakt.
