### ISSUE TITLE
absolvent.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#53]
ciasteczka

![ss212](https://user-images.githubusercontent.com/44813765/49469084-e3320b00-f806-11e8-8683-880f5e7cfd95.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
`absolvent.pl##.top-ban-wrapper`
