### ISSUE TITLE
wikom.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#6]
rodo

![ss206](https://user-images.githubusercontent.com/44813765/49340573-fe075280-f641-11e8-9808-733e0df929a0.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`www.wikom.pl##.law-popup-wrapper`
