### ISSUE TITLE
umig.olkusz.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#78]
Reopen - https://github.com/MajkiIT/polish-ads-filter/issues/9515 

<details not-open>
<summary>Błąd - brak przewijania: </summary>

![ss309](https://user-images.githubusercontent.com/44813765/49658806-31cbe900-fa43-11e8-96ff-34f8b0e458ae.png)

</details>
<br>
<details not-open>
<summary>po wyłączeniu listy jest komunikat rodo:</summary>

![ss311](https://user-images.githubusercontent.com/44813765/49658863-49a36d00-fa43-11e8-8b81-41ebab696813.png)

</details>
<br>
<details not-open>
<summary>Po jego zaakceptowaniu strona ładuje się i jest przewijanie</summary>

![ss312](https://user-images.githubusercontent.com/44813765/49658887-588a1f80-fa43-11e8-9d81-eb57e63e9663.png)

</details>

**Comment by krystian3w** [comment]
`<details not-open><!-- remove 'not-' to start expanded -->`

Jeszcze nie słyszałem o domyślnie otwartym spoilerze, on nawet nie jest stylowany na githubie.

**Comment by krystian3w** [comment]
Bo wyjątek dla adblock plus jak nie znajdę łagodnego filtra sieciowego.

**Comment by gargaamel** [comment]
> krystian3w :
> 
> `<details not-open><!-- remove 'not-' to start expanded -->`
> 
> Jeszcze nie słyszałem o domyślnie otwartym spoilerze, on nawet nie jest stylowany na githubie.

Nie wiem co masz na myśli przez "nie jest stylowany na githubie", ale jeśli chodzi ci o to, że nie jest respektowany, a jeszcze bardziej po chłopsku, że po prostu nie działa, to się mylisz, zobacz:

<details not-open>
<summary>spojler 1 - details not-open - domyślnie zamknięty - strzałka w prawo</summary>

zawartość spoilera

</details>
.
<details open>
<summary>spojler 2 - details open - domyślnie otwarty - strzałka w dół</summary>

zawartość spoilera

</details>
.
<details open>
<summary>spojler 3 - details open - domyślnie otwarty - strzałka w dół, ale się nie otworzy -  bo brak zawartości</summary>



</details>
.

Może zapomniałeś dodać zawartość i był pusty.

**Comment by krystian3w** [comment]
Chodzi mi że specyfikacja html5 raczej zakłada, że jest zamknięty.

Wątpię, że ktoś sobie robi CSS z otwieraczem i ignoruje dopisywany potem przez przeglądarkę atrybut "`open`" tak, że jak ten się pojawi, to jest dopiero zamykany.

**Comment by gargaamel** [comment]
Ja się z kropką męczyłem od zawsze, żeby oddzielić spojlery a zapomniałem o <br>, którym mi poprawiłeś, czasem najciemniej pod latarnią.

**Comment by krystian3w** [comment]
Ostatnio mi się udało jakoś ukośnikiem z markdown ale już nie chce działać :rofl:.

**Comment by krystian3w** [comment]
`gafancybox` aż mnie rozbraja ten plugin że ma odmianę `ga`.

**Comment by gargaamel** [comment]
Lepiej zamykanie zostaw mi, bo ja zawsze sprawdzam przed zamknięciem.

**Comment by krystian3w** [comment]
No to widać pod Chromium z uBlock Origin trzeba rozbić na osobne linie.

Nie używamy body i html by działało też z Nano Adblockerem,

**Comment by krystian3w** [comment]
```
drogeriapigment.pl,bip.badkowo.ug.gov.pl,bip.powiat.poznan.pl,teatrpolski.waw.pl,szpitalnawrzesinie.pl,powiat-zyrardowski.pl,tureckisklep.pl,umig.olkusz.pl,sklepdlalekarza.com##html.fancybox-margin, html.gafancybox-margin:style(margin-right: 0 !important;)
```

```
drogeriapigment.pl,bip.badkowo.ug.gov.pl,bip.powiat.poznan.pl,teatrpolski.waw.pl,szpitalnawrzesinie.pl,powiat-zyrardowski.pl,tureckisklep.pl,umig.olkusz.pl,sklepdlalekarza.com##html.fancybox-lock > body, html.fancybox-lock, html.gafancybox-lock > body, html.gafancybox-lock:style(overflow: auto !important;)
```

Chyba że widzisz błąd z przecinkami do rozdzielnia.

**Comment by krystian3w** [comment]
Chyba, że takie coś rusza w operze i pomaga:

`##html > body, html:style(overflow: auto !important;)`
`##html > body, html:style(margin-right: 0 !important;)`

**Comment by gargaamel** [comment]
Działa w Firefoxie i w Operze.

**Comment by krystian3w** [comment]
`umig.olkusz.pl##html > body, html:style(overflow: auto !important; margin-right: 0 !important;)`

A takie?

**Comment by gargaamel** [comment]
Działa, ale czy nie podublują się style?

**Comment by krystian3w** [comment]
Mnie chodzi jaki selektor CSS, użyć bo mówisz że zły:

`##html.fancybox-margin, html.gafancybox-margin:style(margin-right: 0 !important;)`
`##html.fancybox-lock > body, html.fancybox-lock, html.gafancybox-lock > body, html.gafancybox-lock:style(overflow: auto !important;)`

**Comment by gargaamel** [comment]
Ja nic nie mówiłem takiego, tylko zapytałem z ciekawości, mi to obojętne, który dodasz.

**Comment by krystian3w** [comment]
Napisałeś, że przestało działać jak było też: 

`html.fancybox-margin, html.gafancybox-margin`
`html.fancybox-lock > body, html.fancybox-lock, html.gafancybox-lock > body, html.gafancybox-lock`

Ja wolę takie, bo te prostsze może nie działać w Nano Ablocker / AdGuard bo nie mają userCSS lub źle zaimplementowane.

Nie robimy filtrów CSS / transformacji CSS to nie powinno być lagów.

**Comment by krystian3w** [comment]
Napisałeś, że przestało działać jak było też: 

* `html.fancybox-margin, html.gafancybox-margin`


* `html.fancybox-lock > body,`
 `html.fancybox-lock,`
 `html.gafancybox-lock > body, `
 `html.gafancybox-lock`

Ja wolę takie, bo te prostsze może nie działać w Nano Adblocker / AdGuard bo nie mają, userCSS lub źle zaimplementowane.

Nie robimy filtrów CSS / transformacji CSS to nie powinno być lagów.

**Comment by krystian3w** [comment]
chyba że mam literówkę w "`gafancybox`" np. `ga-fancybox` powinno być.

**Comment by gargaamel** [comment]
> krystian3w : Napisałeś, że przestało działać jak było też:

Bo przestało i teraz też nie działa

> krystian3w : chyba że mam literówkę w "gafancybox" np. ga-fancybox powinno być.

Nawet z tym myślnikiem też nie scrolla nie ma, a bez myślnika pusta biała strona.

**Comment by krystian3w** [comment]
Pierwsze słyszę, by się od resetowania marginesu robiła biała. Od overflow raczej też pierwsze słyszę.

**Comment by gargaamel** [comment]
Myślę, że się nie zrozumieliśmy co do filtrów i coś się popieprzyło, mam tylko prośbę, że jeśli chcesz żebym przetestował jakiś filtr to wklej mi go kompletnego (razem z whitelistingiem filtrów, które są już na liście, żeby je wyłączyć i przetestować tylko te nowe), żebym zrobił tylko copy&paste do Moje Filtry, żebyś nie wklejał jakiś wycinków filtrów, które przed zaaplikowaniem wymagają dodatkowego opracowywania i zagłębiania się w bebechy problemu, bo wtedy są nic dziwnego, że potem są pomyłki i rozbieżności. Na chwilę obecną dalej nie ma marginesu, więc zdejmuję zółtą etykietę.

**Comment by krystian3w** [comment]
```css
umig.olkusz.pl##html.gafancybox-lock > body, html.gafancybox-lock:style(margin-right: 0 !important;)
umig.olkusz.pl##html.gafancybox-margin:style(overflow: auto !important;)
umig.olkusz.pl###gafancybox-overlay174
```

Ja bym to zgłosił do grohilla i jspenguina popytał czy już jest wystarczająco stabilny userCSS.

**Comment by krystian3w** [comment]
O patrz już widzę, resetuje margines przewijaniem, a przewijanie naprawiam marginesem.

:rofl:

**Comment by krystian3w** [comment]
```css
umig.olkusz.pl###gafancybox-overlay174
umig.olkusz.pl##.gafancybox-lock > body, .gafancybox-lock:style(overflow: auto !important;)
umig.olkusz.pl##.gafancybox-margin:style(margin-right: 0 !important;)
```
