### ISSUE TITLE
rik.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#82]
ciasteczka

![ss228](https://user-images.githubusercontent.com/44813765/49684237-4787ef80-fad1-11e8-916b-274894f7a621.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
U mnie nie chce się załadować w Firefox i Chrome, nie mam detekcji blokowania...

**Comment by krystian3w** [comment]
Etykieta o wycinaniu przez przypadek, używam czasem panelu do tych 20 zgłoszeń na listę.

**Comment by krystian3w** [comment]
Daj znać jakby go może Fanboy lub kiboke przywracali a nie że już popsułem świeżo instalowane chrome.

**Comment by krystian3w** [comment]
`rik.pl###ac_cookie_bar`
