### ISSUE TITLE
pozyczkaplus.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#84]
ciasteczka

![ss230](https://user-images.githubusercontent.com/44813765/49689927-f4da2200-fb28-11e8-8702-36e8357d9b90.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
1pozyczkaplus.pl##.cookie`
