### ISSUE TITLE
prisonwars.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#85]
ciasteczka

![ss232](https://user-images.githubusercontent.com/44813765/49690042-a75eb480-fb2a-11e8-9b51-be1e9adf41bc.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
`##div:not([id]):not([class])[style*="position"][style*="fixed"]`
