### ISSUE TITLE
planetawiedzy.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#9]
rodo

![ss213](https://user-images.githubusercontent.com/44813765/49341685-627dde00-f651-11e8-8a09-507d96dd43f7.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`###rodoinfo`

**Comment by gargaamel** [comment]
Dalej to jest.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/d433a1045f1c94c2bb64459d3052085c9305db05

Może się przytkał już uBlock Origin, ja aż muszę ręcznie uruchamiać czasem plik z "`?_=XXXXX`".

I wtedy dopiero widzi uBO nowszą wersje i umie ją pobrać.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/52d68830fda5ac5a9c1834ab879e358a8eb67ae3

**Comment by gargaamel** [comment]
Ten twój sposób z "?_=XXXXX"  zadziałał hehe, no to gitara, ale to tak czy inaczej chyba ten cały bug uBO z nieatkualizowaniem się listy raczej kwalifikuje się do zgłoszenia.

**Comment by krystian3w** [comment]
Na niego nawet te całe CDN-y nie pomagają.
